# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec8fe593a6b4d37da2fe117f9983b0c6b080320db5603213ca7539e21f745c561da9392bdbc473a7da0e430d50362f5db7d80727dd251011d62e68b79d226935

test:
  secret_key_base: 928201663a9a54e919c9ef16295fdcf07466807e8454a7dbce86d5771a691f9211cbe4a54cad3d05a8c6c52e7812bd0aedc5b1488c7dabf7c98f0a8ed8df14c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
